# Generated by Django 2.2.7 on 2020-04-17 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
            ],
        ),
    ]
